# eslint-disable pnpm/yaml-enforce-settings
packages:
  - '.'

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
  workerd: true
